# Generated by Django 5.2.8 on 2025-12-02 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(blank=True, max_length=100, verbose_name='Write your full name')),
                ('customer_address', models.CharField(blank=True, max_length=100, verbose_name='Write your full address')),
                ('supplier_name', models.CharField(blank=True, max_length=100, verbose_name="Write supplier's full name")),
                ('supplier_address', models.CharField(blank=True, max_length=100, verbose_name="Write supplier's full address")),
                ('order_date', models.DateField(auto_now=True)),
                ('products', models.TextField(verbose_name='Write your order on a list')),
                ('notes', models.TextField(verbose_name='Write your notes for the supplier')),
            ],
        ),
    ]
