# Generated by Django 5.2.8 on 2025-12-02 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='order_type',
            field=models.CharField(choices=[('Order', 'Order'), ('Return', 'Return')], default='Order', max_length=20),
        ),
    ]
